# SPDX-FileCopyrightText: 2025 Polonium-bot <admin@ss14.pl>
# SPDX-FileCopyrightText: 2025 nikitosych <174215049+nikitosych@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: VisMPSPistol
  result: VisMPSPistol
  materials:
    Steel: 450
    Plastic: 200

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: VisMPSPistolMagazineEmpty
  result: VisMPSPistolMagazineEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: VisMPSPistolMagazine
  result: VisMPSPistolMagazine
  materials:
    Steel: 145

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: VisMPSPistolMagazinePractice
  result: VisMPSPistolMagazinePractice
  materials:
    Steel: 85

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: VisMPSPistolMagazineUranium
  result: VisMPSPistolMagazineUranium
  materials:
    Steel: 25
    Plastic: 65
    Uranium: 120

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: VisMPSPistolMagazineIncendiary
  result: VisMPSPistolMagazineIncendiary
  materials:
    Steel: 25
    Plastic: 120

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: PMMMachineGunMagazineEmpty
  result: PMMMachineGunMagazineEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PMMMachineGunMagazine
  result: PMMMachineGunMagazine
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PMMMachineGunMagazinePractice
  result: PMMMachineGunMagazinePractice
  materials:
    Steel: 175

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PMMMachineGunMagazineIncendiary
  result: PMMMachineGunMagazineIncendiary
  materials:
    Steel: 20
    Plastic: 250

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: PMMMachineGunMagazineUranium
  result: PMMMachineGunMagazineUranium
  materials:
    Steel: 25
    Plastic: 120
    Uranium: 122

- type: latheRecipe
  parent: BaseEmptyAmmoRecipe
  id: BorSniperMagazineEmpty
  result: BorSniperMagazineEmpty
  materials:
    Steel: 30

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: BorSniperMagazine
  result: BorSniperMagazine
  materials:
    Steel: 400

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponSubMachineGunGlauberyt
  result: WeaponSubMachineGunGlauberyt
  materials:
    Steel: 700
    Plastic: 250
