## SPDX-FileCopyrightText: 2025 Gansu <68031780+GansuLalan@users.noreply.github.com>
## SPDX-FileCopyrightText: 2025 QueerCats <jansencheng3@gmail.com>
## SPDX-FileCopyrightText: 2025 ScarKy0 <scarky0@onet.eu>
## SPDX-FileCopyrightText: 2025 Tiniest Shark <head.rebel@yahoo.com>
## SPDX-FileCopyrightText: 2025 aa5g21 <aa5g21@soton.ac.uk>
## SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
##
## SPDX-License-Identifier: MIT
### Static
#
#TODO refactor to use recipe packs
#
#- type: latheRecipePack
#  id: ServiceStatic
#  recipes:
#  - Bucket
#  - DrinkMug
#  - DrinkMugMetal
#  - DrinkGlass
#  - DrinkShotGlass
#  - DrinkGlassCoupeShaped
#  - CustomDrinkJug
#  - FoodPlate
#  - FoodPlateSmall
#  - FoodPlatePlastic
#  - FoodPlateSmallPlastic
#  - FoodBowlBig
#  - FoodPlateTin
#  - FoodPlateMuffinTin
#  - FoodKebabSkewer
#  - SprayBottle
#  - LightReplacer
#  - MopItem
#  - Holoprojector
#  - WetFloorSign
#
#- type: latheRecipePack
#  id: ServiceBoardsStatic
#  recipes:
#  - BiogeneratorMachineCircuitboard
#  - UniformPrinterMachineCircuitboard
#  - MicrowaveMachineCircuitboard
#  - ReagentGrinderMachineCircuitboard
#  - ElectricGrillMachineCircuitboard
#  - BoozeDispenserMachineCircuitboard
#  - SodaDispenserMachineCircuitboard
#
#- type: latheRecipePack
#  id: HydroponicsStatic
#  recipes:
#  - HydroponicsToolMiniHoe
#  - HydroponicsToolScythe
#  - HydroponicsToolHatchet
#  - HydroponicsToolSpade
#  - HydroponicsToolClippers
#  - PlantAnalyzer
#
### Dynamic
#
#- type: latheRecipePack
#  id: Janitor
#  recipes:
#  - AdvMopItem
#  - WeaponSprayNozzle
#  - ClothingBackpackWaterTank
#  - MegaSprayBottle
#
#- type: latheRecipePack
#  id: Instruments
#  recipes:
#  - SynthesizerInstrument
#
#- type: latheRecipePack
#  id: Cartridge
#  recipes:
#  - PlantScanCartridge
#
#- type: latheRecipePack
#  id: ServiceBoards
#  recipes:
#  - BiofabricatorMachineCircuitboard
#  - FatExtractorMachineCircuitboard
#  - HydroponicsTrayMachineCircuitboard # roundstart gear being unlocked roundstart when
#  - SeedExtractorMachineCircuitboard # ^
#  - MassMediaCircuitboard
#  - ReagentGrinderIndustrialMachineCircuitboard
#  - JukeboxCircuitBoard
#  - DawInstrumentMachineCircuitboard
